#ifndef __DEVICE_H__
#define __DEVICE_H__

#define MOON_MODE 1
#define HDSR      1

#ifndef TETRAS3_CAMERA_INFO_LIST
#ifndef TETRAS3_CAMERA_INFO_LIST_WIDE
#ifndef TETRAS3_CAMERA_INFO_LIST_WIDE_INDEX
#define TETRAS3_CAMERA_INFO_LIST_WIDE_INDEX RoleIdRearWide
#endif
#ifndef TETRAS3_CAMERA_INFO_LIST_WIDE_VALUE
#ifndef TETRAS3_CAMERA_INFO_LIST_WIDE_ID
#define TETRAS3_CAMERA_INFO_LIST_WIDE_ID SR_CAMERA_ID_L2_WIDE_IMX707
#endif
#ifndef TETRAS3_CAMERA_INFO_LIST_WIDE_NAME
#define TETRAS3_CAMERA_INFO_LIST_WIDE_NAME "wide"
#endif
#ifndef TETRAS3_CAMERA_INFO_LIST_WIDE_PIXEL_DEPTH
#define TETRAS3_CAMERA_INFO_LIST_WIDE_PIXEL_DEPTH PIXEL_DEPTH_8BIT
#endif
#define TETRAS3_CAMERA_INFO_LIST_WIDE_VALUE                                   \
    {                                                                         \
        TETRAS3_CAMERA_INFO_LIST_WIDE_ID, TETRAS3_CAMERA_INFO_LIST_WIDE_NAME, \
            TETRAS3_CAMERA_INFO_LIST_WIDE_PIXEL_DEPTH                         \
    }
#endif
#define TETRAS3_CAMERA_INFO_LIST_WIDE \
    [TETRAS3_CAMERA_INFO_LIST_WIDE_INDEX] = TETRAS3_CAMERA_INFO_LIST_WIDE_VALUE
#endif

#ifndef TETRAS3_CAMERA_INFO_LIST_TELE
#ifndef TETRAS3_CAMERA_INFO_LIST_TELE_INDEX
#define TETRAS3_CAMERA_INFO_LIST_TELE_INDEX RoleIdRearTele
#endif

#ifndef TETRAS3_CAMERA_INFO_LIST_TELE_VALUE
#ifndef TETRAS3_CAMERA_INFO_LIST_TELE_ID
#define TETRAS3_CAMERA_INFO_LIST_TELE_ID SR_CAMERA_ID_L2_2X_JN1
#endif
#ifndef TETRAS3_CAMERA_INFO_LIST_TELE_NAME
#define TETRAS3_CAMERA_INFO_LIST_TELE_NAME "tele"
#endif
#ifndef TETRAS3_CAMERA_INFO_LIST_TELE_PIXEL_DEPTH
#define TETRAS3_CAMERA_INFO_LIST_TELE_PIXEL_DEPTH PIXEL_DEPTH_8BIT
#endif
#define TETRAS3_CAMERA_INFO_LIST_TELE_VALUE                                   \
    {                                                                         \
        TETRAS3_CAMERA_INFO_LIST_TELE_ID, TETRAS3_CAMERA_INFO_LIST_TELE_NAME, \
            TETRAS3_CAMERA_INFO_LIST_TELE_PIXEL_DEPTH                         \
    }
#endif
#define TETRAS3_CAMERA_INFO_LIST_TELE \
    [TETRAS3_CAMERA_INFO_LIST_TELE_INDEX] = TETRAS3_CAMERA_INFO_LIST_TELE_VALUE

#ifndef TETRAS3_CAMERA_INFO_LIST_MOON
#ifndef TETRAS3_CAMERA_INFO_LIST_MOON_INDEX
#define TETRAS3_CAMERA_INFO_LIST_MOON_INDEX 2
#endif

#ifndef TETRAS3_CAMERA_INFO_LIST_MOON_VALUE
#ifndef TETRAS3_CAMERA_INFO_LIST_MOON_VALUE_ID
#define TETRAS3_CAMERA_INFO_LIST_MOON_VALUE_ID SR_CAMERA_ID_L2_2X_JN1_MOON
#endif
#ifndef TETRAS3_CAMERA_INFO_LIST_MOON_VALUE_NAME
#define TETRAS3_CAMERA_INFO_LIST_MOON_VALUE_NAME "moon"
#endif
#ifndef TETRAS3_CAMERA_INFO_LIST_MOON_VALUE_PIXEL_DEPTH
#define TETRAS3_CAMERA_INFO_LIST_MOON_VALUE_PIXEL_DEPTH PIXEL_DEPTH_8BIT
#endif
#define TETRAS3_CAMERA_INFO_LIST_MOON_VALUE                                               \
    {                                                                                     \
        TETRAS3_CAMERA_INFO_LIST_MOON_VALUE_ID, TETRAS3_CAMERA_INFO_LIST_MOON_VALUE_NAME, \
            TETRAS3_CAMERA_INFO_LIST_MOON_VALUE_PIXEL_DEPTH                               \
    }
#endif
#define TETRAS3_CAMERA_INFO_LIST_MOON \
    [TETRAS3_CAMERA_INFO_LIST_MOON_INDEX] = TETRAS3_CAMERA_INFO_LIST_MOON_VALUE
#endif
#endif

#define TETRAS3_CAMERA_INFO_LIST                                      \
    {                                                                 \
        TETRAS3_CAMERA_INFO_LIST_WIDE, TETRAS3_CAMERA_INFO_LIST_TELE, \
            TETRAS3_CAMERA_INFO_LIST_MOON,                            \
    }
#endif

#endif
