/*
 * @file        morpho_image_format.h
 * @brief        Image format enum definition
 * @version     v1.0.0
 * @date         2019-12-24
 *
 *    Copyright(c) 2019 Morpho China,Inc.
 */

#ifndef _MORPHO_IMAGE_FORMAT_H
#define _MORPHO_IMAGE_FORMAT_H

#ifdef __cplusplus
extern "C" {
#endif

#define MORPHO_IMAGE_FORMAT_NONE_STR                      "NONE"
#define MORPHO_IMAGE_FORMAT_UINT8_STR                     "UINT8"
#define MORPHO_IMAGE_FORMAT_INT16_STR                     "INT16"
#define MORPHO_IMAGE_FORMAT_UINT16_STR                    "UINT16"
#define MORPHO_IMAGE_FORMAT_INT32_STR                     "INT32"
#define MORPHO_IMAGE_FORMAT_FLOAT_STR                     "FLOAT"
#define MORPHO_IMAGE_FORMAT_UINT88_STR                    "UINT88"
#define MORPHO_IMAGE_FORMAT_UINT1616_STR                  "UINT1616"
#define MORPHO_IMAGE_FORMAT_RGB565_STR                    "RGB565"
#define MORPHO_IMAGE_FORMAT_RGB888_STR                    "RGB888"
#define MORPHO_IMAGE_FORMAT_BGR888_STR                    "RGBA8888"
#define MORPHO_IMAGE_FORMAT_RGBA8888_STR                  "RGBA8888"
#define MORPHO_IMAGE_FORMAT_RBGA8888_STR                  "RBGA8888"
#define MORPHO_IMAGE_FORMAT_GRBA8888_STR                  "GRBA8888"
#define MORPHO_IMAGE_FORMAT_GBRA8888_STR                  "GBRA8888"
#define MORPHO_IMAGE_FORMAT_BRGA8888_STR                  "BRGA8888"
#define MORPHO_IMAGE_FORMAT_BGRA8888_STR                  "BGRA8888"
#define MORPHO_IMAGE_FORMAT_ARGB8888_STR                  "ARGB8888"
#define MORPHO_IMAGE_FORMAT_ARBG8888_STR                  "ARBG8888"
#define MORPHO_IMAGE_FORMAT_AGRB8888_STR                  "AGRB8888"
#define MORPHO_IMAGE_FORMAT_AGBR8888_STR                  "AGBR8888"
#define MORPHO_IMAGE_FORMAT_ABRG8888_STR                  "ABRG8888"
#define MORPHO_IMAGE_FORMAT_ABGR8888_STR                  "ABGR8888"
#define MORPHO_IMAGE_FORMAT_RGB10B_PACKED_LE_XBGR_STR     "RGB10B_PACKED_LE_XBGR"
#define MORPHO_IMAGE_FORMAT_RGB161616_STR                 "RGB161616"
#define MORPHO_IMAGE_FORMAT_RGBA32F_STR                   "RGBA32F"
#define MORPHO_IMAGE_FORMAT_BGRA32F_STR                   "BGRA32F"
#define MORPHO_IMAGE_FORMAT_ARGB32F_STR                   "ARGB32F"
#define MORPHO_IMAGE_FORMAT_ABGR32F_STR                   "ABGR32F"
#define MORPHO_IMAGE_FORMAT_YUV444_YUV_STR                "YUV444_YUV"
#define MORPHO_IMAGE_FORMAT_YUV444_YVU_STR                "YUV444_YVU"
#define MORPHO_IMAGE_FORMAT_YUV444_UYV_STR                "YUV444_UYV"
#define MORPHO_IMAGE_FORMAT_YUV444_VYU_STR                "YUV444_VYU"
#define MORPHO_IMAGE_FORMAT_YUV444_UVY_STR                "YUV444_UVY"
#define MORPHO_IMAGE_FORMAT_YUV444_VUY_STR                "YUV444_VUY"
#define MORPHO_IMAGE_FORMAT_YUV444_PLANAR_STR             "YUV444_PLANAR"
#define MORPHO_IMAGE_FORMAT_YUV422_YUYV_STR               "YUV422_YUYV"
#define MORPHO_IMAGE_FORMAT_YUV422_YVYU_STR               "YUV422_YVYU"
#define MORPHO_IMAGE_FORMAT_YUV422_UYVY_STR               "YUV422_UYVY"
#define MORPHO_IMAGE_FORMAT_YUV422_VYUY_STR               "YUV422_VYUY"
#define MORPHO_IMAGE_FORMAT_YUV422_YYUV_STR               "YUV422_YYUV"
#define MORPHO_IMAGE_FORMAT_YUV422_YYVU_STR               "YUV422_YYVU"
#define MORPHO_IMAGE_FORMAT_YUV422_UVYY_STR               "YUV422_UVYY"
#define MORPHO_IMAGE_FORMAT_YUV422_VUYY_STR               "YUV422_VUYY"
#define MORPHO_IMAGE_FORMAT_YUV422_PLANAR_STR             "YUV422_PLANAR"
#define MORPHO_IMAGE_FORMAT_YUV422_SEMIPLANAR_STR         "YUV422_SEMIPLANAR"
#define MORPHO_IMAGE_FORMAT_YVU422_SEMIPLANAR_STR         "YVU422_SEMIPLANAR"
#define MORPHO_IMAGE_FORMAT_YUV420_PLANAR_STR             "UV420_PLANAR"
#define MORPHO_IMAGE_FORMAT_YUV420_SEMIPLANAR_STR         "YUV420_SEMIPLANAR"
#define MORPHO_IMAGE_FORMAT_YVU420_SEMIPLANAR_STR         "YVU420_SEMIPLANAR"
#define MORPHO_IMAGE_FORMAT_YUV10B422_PLANAR_STR          "YUV10B422_PLANAR"
#define MORPHO_IMAGE_FORMAT_YUV10B420_PLANAR_STR          "YUV10B420_PLANAR"
#define MORPHO_IMAGE_FORMAT_YUV10B420_SEMIPLANAR_STR      "YUV10B420_SEMIPLANAR"
#define MORPHO_IMAGE_FORMAT_YVU10B420_SEMIPLANAR_STR      "YVU10B420_SEMIPLANAR"
#define MORPHO_IMAGE_FORMAT_YUV10B_PACKED_LE_422_YUYV_STR "YUV10B_PACKED_LE_422_YUYV"
#define MORPHO_IMAGE_FORMAT_YUV10B_PACKED_LE_422_YVYU_STR "YUV10B_PACKED_LE_422_YVYU"
#define MORPHO_IMAGE_FORMAT_YUV10B_PACKED_LE_422_UYVY_STR "YUV10B_PACKED_LE_422_UYVY"
#define MORPHO_IMAGE_FORMAT_YUV10B_PACKED_LE_422_VYUY_STR "YUV10B_PACKED_LE_422_VYUY"
#define MORPHO_IMAGE_FORMAT_YUV10B_PACKED_LE_422_YYUV_STR "YUV10B_PACKED_LE_422_YYUV"
#define MORPHO_IMAGE_FORMAT_YUV10B_PACKED_LE_422_YYVU_STR "YUV10B_PACKED_LE_422_YYVU"
#define MORPHO_IMAGE_FORMAT_YUV10B_PACKED_LE_422_UVYY_STR "YUV10B_PACKED_LE_422_UVYY"
#define MORPHO_IMAGE_FORMAT_YUV10B_PACKED_LE_422_VUYY_STR "YUV10B_PACKED_LE_422_VUYY"
#define MORPHO_IMAGE_FORMAT_YUV10B_PACKED_LE_420S_STR     "YUV10B_PACKED_LE_420S"
#define MORPHO_IMAGE_FORMAT_YUV16B444_PLANAR_STR          "YUV16B444_PLANAR"
#define MORPHO_IMAGE_FORMAT_YUV16B422_PLANAR_STR          "YUV16B422_PLANAR"
#define MORPHO_IMAGE_FORMAT_YUV16B420_SEMIPLANAR_STR      "YUV16B420_SEMIPLANAR"
#define MORPHO_IMAGE_FORMAT_YVU16B420_SEMIPLANAR_STR      "YVU16B420_SEMIPLANAR"
#define MORPHO_IMAGE_FORMAT_YUV32F422_PLANAR_STR          "YUV32F422_PLANAR"
#define MORPHO_IMAGE_FORMAT_BAYER8_RGGB_STR               "BAYER8_RGGB"
#define MORPHO_IMAGE_FORMAT_BAYER8_GRBG_STR               "BAYER8_GRBG"
#define MORPHO_IMAGE_FORMAT_BAYER8_GBRG_STR               "BAYER8_GBRG"
#define MORPHO_IMAGE_FORMAT_BAYER8_BGGR_STR               "BAYER8_BGGR"
#define MORPHO_IMAGE_FORMAT_BAYER10_UNPACKED_RGGB_STR     "BAYER10_UNPACKED_RGGB"
#define MORPHO_IMAGE_FORMAT_BAYER10_UNPACKED_GRBG_STR     "BAYER10_UNPACKED_GRBG"
#define MORPHO_IMAGE_FORMAT_BAYER10_UNPACKED_GBRG_STR     "BAYER10_UNPACKED_GBRG"
#define MORPHO_IMAGE_FORMAT_BAYER10_UNPACKED_BGGR_STR     "BAYER10_UNPACKED_BGGR"
#define MORPHO_IMAGE_FORMAT_BAYER10_M8L2PACKED_RGGB_STR   "BAYER10_M8L2PACKED_RGGB"
#define MORPHO_IMAGE_FORMAT_BAYER10_M8L2PACKED_GRBG_STR   "BAYER10_M8L2PACKED_GRBG"
#define MORPHO_IMAGE_FORMAT_BAYER10_M8L2PACKED_GBRG_STR   "BAYER10_M8L2PACKED_GBRG"
#define MORPHO_IMAGE_FORMAT_BAYER10_M8L2PACKED_BGGR_STR   "BAYER10_M8L2PACKED_BGGR"
#define MORPHO_IMAGE_FORMAT_BAYER12_UNPACKED_RGGB_STR     "BAYER12_UNPACKED_RGGB"
#define MORPHO_IMAGE_FORMAT_BAYER12_UNPACKED_GRBG_STR     "BAYER12_UNPACKED_GRBG"
#define MORPHO_IMAGE_FORMAT_BAYER12_UNPACKED_GBRG_STR     "BAYER12_UNPACKED_GBRG"
#define MORPHO_IMAGE_FORMAT_BAYER12_UNPACKED_BGGR_STR     "BAYER12_UNPACKED_BGGR"
#define MORPHO_IMAGE_FORMAT_BAYER16_RGGB_STR              "BAYER16_RGGB"
#define MORPHO_IMAGE_FORMAT_BAYER16_GRBG_STR              "BAYER16_GRBG"
#define MORPHO_IMAGE_FORMAT_BAYER16_GBRG_STR              "BAYER16_GBRG"
#define MORPHO_IMAGE_FORMAT_BAYER16_BGGR_STR              "BAYER16_BGGR"
#define MORPHO_IMAGE_FORMAT_HSV_STR                       "HSV"
#define MORPHO_IMAGE_FORMAT_LAB_STR                       "LAB"

typedef enum _morpho_ImageFormat {

    MORPHO_IMAGE_FORMAT_NONE = 0,

    // INDEX = 1
    MORPHO_IMAGE_FORMAT_UINT8,
    MORPHO_IMAGE_FORMAT_INT16,
    MORPHO_IMAGE_FORMAT_UINT16,
    MORPHO_IMAGE_FORMAT_INT32,
    MORPHO_IMAGE_FORMAT_FLOAT,
    MORPHO_IMAGE_FORMAT_UINT88,
    MORPHO_IMAGE_FORMAT_UINT1616,

    // INDEX = 8
    MORPHO_IMAGE_FORMAT_RGB565,
    MORPHO_IMAGE_FORMAT_RGB888,
    MORPHO_IMAGE_FORMAT_BGR888,

    // INDEX = 11
    MORPHO_IMAGE_FORMAT_RGBA8888,
    MORPHO_IMAGE_FORMAT_RBGA8888,
    MORPHO_IMAGE_FORMAT_GRBA8888,
    MORPHO_IMAGE_FORMAT_GBRA8888,
    MORPHO_IMAGE_FORMAT_BRGA8888,
    MORPHO_IMAGE_FORMAT_BGRA8888,
    MORPHO_IMAGE_FORMAT_ARGB8888,
    MORPHO_IMAGE_FORMAT_ARBG8888,
    MORPHO_IMAGE_FORMAT_AGRB8888,
    MORPHO_IMAGE_FORMAT_AGBR8888,
    MORPHO_IMAGE_FORMAT_ABRG8888,
    MORPHO_IMAGE_FORMAT_ABGR8888,

    // INDEX = 23
    MORPHO_IMAGE_FORMAT_RGB10B_PACKED_LE_XBGR,
    MORPHO_IMAGE_FORMAT_RGB161616,
    MORPHO_IMAGE_FORMAT_RGBA32F,
    MORPHO_IMAGE_FORMAT_BGRA32F,
    MORPHO_IMAGE_FORMAT_ARGB32F,
    MORPHO_IMAGE_FORMAT_ABGR32F,

    // INDEX = 29
    MORPHO_IMAGE_FORMAT_YUV444_YUV,
    MORPHO_IMAGE_FORMAT_YUV444_YVU,
    MORPHO_IMAGE_FORMAT_YUV444_UYV,
    MORPHO_IMAGE_FORMAT_YUV444_VYU,
    MORPHO_IMAGE_FORMAT_YUV444_UVY,
    MORPHO_IMAGE_FORMAT_YUV444_VUY,
    MORPHO_IMAGE_FORMAT_YUV444_PLANAR,

    // INDEX = 36
    MORPHO_IMAGE_FORMAT_YUV422_YUYV,
    MORPHO_IMAGE_FORMAT_YUV422_YVYU,
    MORPHO_IMAGE_FORMAT_YUV422_UYVY,
    MORPHO_IMAGE_FORMAT_YUV422_VYUY,
    MORPHO_IMAGE_FORMAT_YUV422_YYUV,
    MORPHO_IMAGE_FORMAT_YUV422_YYVU,
    MORPHO_IMAGE_FORMAT_YUV422_UVYY,
    MORPHO_IMAGE_FORMAT_YUV422_VUYY,
    MORPHO_IMAGE_FORMAT_YUV422_PLANAR,
    MORPHO_IMAGE_FORMAT_YUV422_SEMIPLANAR,
    MORPHO_IMAGE_FORMAT_YVU422_SEMIPLANAR,

    // INDEX =  47
    MORPHO_IMAGE_FORMAT_YUV420_PLANAR,
    MORPHO_IMAGE_FORMAT_YUV420_SEMIPLANAR,
    MORPHO_IMAGE_FORMAT_YVU420_SEMIPLANAR,

    // INDEX = 50
    MORPHO_IMAGE_FORMAT_YUV10B422_PLANAR,
    MORPHO_IMAGE_FORMAT_YUV10B420_PLANAR,
    MORPHO_IMAGE_FORMAT_YUV10B420_SEMIPLANAR,
    MORPHO_IMAGE_FORMAT_YVU10B420_SEMIPLANAR,

    // INDEX = 54
    MORPHO_IMAGE_FORMAT_YUV10B_PACKED_LE_422_YUYV,
    MORPHO_IMAGE_FORMAT_YUV10B_PACKED_LE_422_YVYU,
    MORPHO_IMAGE_FORMAT_YUV10B_PACKED_LE_422_UYVY,
    MORPHO_IMAGE_FORMAT_YUV10B_PACKED_LE_422_VYUY,
    MORPHO_IMAGE_FORMAT_YUV10B_PACKED_LE_422_YYUV,
    MORPHO_IMAGE_FORMAT_YUV10B_PACKED_LE_422_YYVU,
    MORPHO_IMAGE_FORMAT_YUV10B_PACKED_LE_422_UVYY,
    MORPHO_IMAGE_FORMAT_YUV10B_PACKED_LE_422_VUYY,
    MORPHO_IMAGE_FORMAT_YUV10B_PACKED_LE_420S,

    // INDEX= 63
    MORPHO_IMAGE_FORMAT_YUV16B444_PLANAR,
    MORPHO_IMAGE_FORMAT_YUV16B422_PLANAR,
    MORPHO_IMAGE_FORMAT_YUV16B420_SEMIPLANAR,
    MORPHO_IMAGE_FORMAT_YVU16B420_SEMIPLANAR,

    // INDEX = 67
    MORPHO_IMAGE_FORMAT_YUV32F422_PLANAR,

    // INDEX = 68
    MORPHO_IMAGE_FORMAT_BAYER8_RGGB,
    MORPHO_IMAGE_FORMAT_BAYER8_GRBG,
    MORPHO_IMAGE_FORMAT_BAYER8_GBRG,
    MORPHO_IMAGE_FORMAT_BAYER8_BGGR,

    // INDEX = 72
    MORPHO_IMAGE_FORMAT_BAYER10_UNPACKED_RGGB,
    MORPHO_IMAGE_FORMAT_BAYER10_UNPACKED_GRBG,
    MORPHO_IMAGE_FORMAT_BAYER10_UNPACKED_GBRG,
    MORPHO_IMAGE_FORMAT_BAYER10_UNPACKED_BGGR,

    // INDEX = 76
    MORPHO_IMAGE_FORMAT_BAYER10_M8L2PACKED_RGGB,
    MORPHO_IMAGE_FORMAT_BAYER10_M8L2PACKED_GRBG,
    MORPHO_IMAGE_FORMAT_BAYER10_M8L2PACKED_GBRG,
    MORPHO_IMAGE_FORMAT_BAYER10_M8L2PACKED_BGGR,

    // INDEX = 80
    MORPHO_IMAGE_FORMAT_BAYER12_UNPACKED_RGGB,
    MORPHO_IMAGE_FORMAT_BAYER12_UNPACKED_GRBG,
    MORPHO_IMAGE_FORMAT_BAYER12_UNPACKED_GBRG,
    MORPHO_IMAGE_FORMAT_BAYER12_UNPACKED_BGGR,

    // INDEX = 83
    MORPHO_IMAGE_FORMAT_BAYER16_RGGB,
    MORPHO_IMAGE_FORMAT_BAYER16_GRBG,
    MORPHO_IMAGE_FORMAT_BAYER16_GBRG,
    MORPHO_IMAGE_FORMAT_BAYER16_BGGR,

    // INDEX = 87
    MORPHO_IMAGE_FORMAT_HSV,
    MORPHO_IMAGE_FORMAT_LAB,

    MORPHO_IMAGE_FORMAT_MAX
} morpho_ImageFormat;

#ifdef __cplusplus
} /* extern "C" { */
#endif
#endif /* _MORPHO_IMAGE_FORMAT_H */
