
#if defined(MATISSE_CAMERA) || defined(RUBENS_CAMERA) || defined(YUECHU_CAMERA)
#define ARC_MFSR_CAMERA_TYPE_REAR_WIDE_0    0x00 // L11_HM2
#define ARC_MFSR_CAMERA_TYPE_REAR_WIDE_0_RM 0x01 // L11_HM2 RM mode
#define ARC_MFSR_CAMERA_TYPE_REAR_WIDE_1    0x10 // L11A_IMX582
#define ARC_MFSR_CAMERA_TYPE_REAR_WIDE_1_RM 0x11 // L11A_IMX582 RM mode
#elif defined(PLATO_CAMERA)
#define ARC_MFSR_CAMERA_TYPE_REAR_WIDE_0    0x00
#define ARC_MFSR_CAMERA_TYPE_REAR_WIDE_0_RM 0x01
#elif defined(DAUMIER_CAMERA)
#define ARC_MFSR_CAMERA_TYPE_REAR_WIDE_0    0x00
#define ARC_MFSR_CAMERA_TYPE_REAR_WIDE_0_RM 0x01
#else
#define ARC_MFSR_CAMERA_TYPE_REAR_WIDE_0    0x00
#define ARC_MFSR_CAMERA_TYPE_REAR_WIDE_0_RM 0x01
#endif