/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiaomi_engine_MiaNodeJNI */

#ifndef _Included_com_xiaomi_engine_MiaNodeJNI
#define _Included_com_xiaomi_engine_MiaNodeJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xiaomi_engine_MiaNodeJNI
 * Method:    init
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_xiaomi_engine_MiaNodeJNI_init
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_xiaomi_engine_MiaNodeJNI
 * Method:    processRequest
 * Signature: (Ljava/util/List;Landroid.media.Image;I)I
 */
JNIEXPORT jint JNICALL Java_com_xiaomi_engine_MiaNodeJNI_processRequest
  (JNIEnv *, jclass, jobject, jobject, jint, jboolean);

/*
 * Class:     com_xiaomi_engine_MiaNodeJNI
 * Method:    deInit
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_xiaomi_engine_MiaNodeJNI_deInit
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
